### ISSUE TITLE
Foc constructor not shown in docs.rs

### ISSUE THREAD

**Issue by Ben-PH** [calebfletcher/foc#2]
It's weird, but at time of writing, `foc::Foc::new` is not coming up: https://docs.rs/foc/latest/foc/struct.Foc.html

I think it's because it was added as part of commit e4bf72f4704338e465bb078a1e439b4e3faa6f77, but that commit didn't come with a version bump.

This is problematic, in that Foc has private fields, so cannot be constructed without a method, but when you search docs.rs for `Foc` and check return types, there is nothing, nor could I find a way to access one through a field of another struct.

**Comment by calebfletcher** [comment]
That is correct, see the last bit of my reply here https://github.com/calebfletcher/foc/issues/1#issuecomment-2107104707. I'll be looking to make a new release soon which should have the Foc struct usable from user-facing code and with more robust PI controllers.

**Comment by calebfletcher** [comment]
I've released version 0.3.0 which includes the constructor for `foc::Foc` and for the `pid::PIController` that you need for that struct.
